export const eracleaData = [
  {
    id: "1",
    title: {
      italian: "Eraclea Minoa",
      english: "Eraclea Minoa",
      french: "Eraclea Minoa",
      spanish: "Eraclea Minoa",
    },
    image: "/assets/card_minoa.webp",
    roadmap: "/eraclea_page",
    subcategory: [
      {
        id: "1-1",
        title: {
          italian: "Eraclea Minoa",
          english: "Eraclea Minoa",
          french: "Eraclea Minoa",
          spanish: "Eraclea Minoa",
        },
        images: ["/assets/card_minoa.webp", "/assets/platani.webp"],
        description: {
          italian:
            "Lo storiografo greco Erodoto, nel V secolo a.C., narra dell’antica città di Minoa, che sarebbe stata fondata dagli abitanti di Selinunte e chiamata Eraclea in onore dell’eroe semidio. I ritrovamenti archeologici raccontano, però, una storia molto più antica del territorio ed estremamente affascinante. L’area archeologica è in una magnifica posizione, in una riserva naturale, sul promontorio del capo Bianco (a 75 m), di candida falesia (ripida scarpata scoscesa) di roccia calcarea che si protende sul mare, degradando a ovest verso la valle del Plàtani e a est verso la spiaggia. I frammenti rinvenuti negli strati sottostanti alla Necropoli arcaica del VI secolo a.C. farebbero risalire l’origine dell’insediamento urbano alla preistoria, e precisamente al Neolitico (dall’8000 al 3.500 a.C. circa), mentre le antiche monete ritrovate testimoniano la presenza di una colonia fenicia. Nelle prime fonti storiche, la città è indicata con tre nomi: Macara, ovvero città di Makar, l’Eracle fenicio; Minoa, appunto, che sarebbe stata fondata, secondo la leggenda, dal re di Creta Minosse, che avrebbe inseguito Dedalo fin qui; infine Eraclea, colonia spartana a conferma dell’intitolazione del luogo al grande eroe greco. Dopo i fenici e gli spartani, nel V secolo a.C., la città divenne subcolonia di Selinunte e raggiunse l’apice del suo sviluppo in epoca ellenistica (fine IV secolo a.C.). A lungo contesa tra greci e cartaginesi per la sua posizione strategica di confine, passò di mano più volte, finché, nel 210 a.C., fu conquistata dai Romani. Nel I secolo a.C. venne definitivamente abbandonata, forse a causa di una frana che trascinò in mare la parte meridionale dell’abitato e delle mura. Le indagini archeologiche, ai primi del ‘900, hanno portato alla luce una parte del quartiere residenziale, con tracce leggibili in due stratificazioni successive, della città arcaica ed ellenistica, il tratto settentrionale della cinta muraria, con resti di torri e di porte, e il bel teatro col proscenio aperto verso il mare (in parte nascosto da una struttura protettiva). Nell’Antiquarium, all’ingresso della zona archeologica, è esposto il materiale proveniente dalle abitazioni e dalle Necropoli arcaica ed ellenistica. Il paese, collocato più in basso rispetto al sito archeologico, ospita strutture turistiche e ricettive, tra cui un campeggio, all’ombra di un bosco di eucalipti. La spiaggia si allunga ad anfiteatro fino alle pareti di roccia di capo Bianco, che, con i suoi fanghi, offre ai bagnanti trattamenti cosmetici naturali e gratuiti, all’aria aperta.",
          english:
            "The Greek historian Herodotus, in the 5th century BC, tells of the ancient city of Minoa, which was founded by the inhabitants of Selinunte and called Eraclea in honor of the demigod hero. However, archaeological finds tell a much older and extremely fascinating story of the territory. The archaeological area is in a magnificent position, in a nature reserve, on the promontory of Capo Bianco (at 75 m), of a white cliff (steep slope) of limestone rock that juts out into the sea, sloping west towards the Plàtani valley and east towards the beach. The fragments found in the layers beneath the archaic necropolis of the 6th century BC would date the origin of the urban settlement back to prehistory, and precisely to the Neolithic (from 8000 to 3500 BC approximately), while the ancient coins found testify to the presence of a Phoenician colony. In the first historical sources, the city is indicated by three names: Macara, or city of Makar, the Phoenician Heracles; Minoa, in fact, which was founded, according to legend, by the king of Crete Minos, who chased Daedalus here; finally Eraclea, a Spartan colony confirming the dedication of the place to the great Greek hero. After the Phoenicians and the Spartans, in the 5th century BC, the city became a sub-colony of Selinunte and reached the peak of its development in the Hellenistic era (late 4th century BC). Long disputed between the Greeks and the Carthaginians for its strategic border position, it changed hands several times, until, in 210 BC, it was conquered by the Romans. In the 1st century BC it was finally abandoned, perhaps because of a landslide that dragged the southern part of the town and the walls into the sea. Archaeological investigations, at the beginning of the 20th century, brought to light a part of the residential district, with traces legible in two successive stratifications, of the archaic and Hellenistic city, the northern stretch of the city walls, with remains of towers and gates, and the beautiful theater with the proscenium open towards the sea (partly hidden by a protective structure). In the Antiquarium, at the entrance to the archaeological area, the material from the homes and the archaic and Hellenistic necropolis is exhibited. The town, located lower than the archaeological site, hosts tourist and accommodation facilities, including a campsite, in the shade of a eucalyptus forest. The beach extends like an amphitheater up to the rock walls of Capo Bianco, which, with its mud, offers bathers natural and free cosmetic treatments, in the open air.",
          french:
            "L'historiographe grec Hérodote, au Ve siècle avant JC, parle de l'ancienne ville de Minoa, fondée par les habitants de Sélinonte et appelée Héraclée en l'honneur du héros demi-dieu. Les découvertes archéologiques racontent cependant une histoire beaucoup plus ancienne et extrêmement fascinante de la région. La zone archéologique se trouve dans une position magnifique, dans une réserve naturelle, sur le promontoire de Capo Bianco (à 75 m), avec une falaise de calcaire blanc (pente raide) qui s'avance dans la mer, en pente ouest vers la vallée de Plàtani et à l'est vers la plage. Les fragments trouvés dans les couches sous la nécropole archaïque du 6ème siècle avant JC. ferait remonter les origines de l'habitat urbain à la préhistoire, et précisément au Néolithique (d'environ 8000 à 3500 avant JC), tandis que les monnaies anciennes trouvées témoignent de la présence d'une colonie phénicienne. Dans les premières sources historiques, la ville est indiquée par trois noms : Macara, ou ville de Makar, l'Héraclès phénicien ; Minoa, en effet, qui a été fondée, selon la légende, par le roi de Crète Minos, qui y pourchassait Dédale ; enfin Eraclea, colonie spartiate confirmant le nom du lieu en hommage au grand héros grec. Après les Phéniciens et les Spartiates, au Vème siècle avant JC, la ville devint une sous-colonie de Sélinonte et atteignit l'apogée de son développement à l'époque hellénistique (fin du IVème siècle avant JC). Longtemps disputée entre Grecs et Carthaginois pour sa position frontalière stratégique, elle changea plusieurs fois de mains jusqu'à ce qu'en 210 avant JC elle soit conquise par les Romains. Au 1er siècle avant JC elle fut définitivement abandonnée, peut-être à cause d'un glissement de terrain qui entraîna la partie sud de la ville et les murailles dans la mer. Des fouilles archéologiques, au début du XXe siècle, ont mis au jour une partie du quartier résidentiel, avec des traces lisibles dans deux stratifications successives, de la ville archaïque et hellénistique, la partie nord des remparts de la ville, avec des restes de tours et de portes. , et le beau théâtre avec l'avant-scène ouvert sur la mer (en partie caché par une structure de protection). Dans l'Antiquarium, à l'entrée de la zone archéologique, sont exposés des matériaux provenant des maisons et des nécropoles archaïques et hellénistique. La commune, située en contrebas du site archéologique, accueille des installations touristiques et d'hébergement, dont un camping, à l'ombre d'une forêt d'eucalyptus. La plage s'étend en amphithéâtre jusqu'aux parois rocheuses de Capo Bianco, qui, avec sa boue, offre aux baigneurs des soins cosmétiques naturels et gratuits en plein air.",
          spanish:
            "El historiógrafo griego Heródoto, en el siglo V a.C., habla de la antigua ciudad de Minoa, que fue fundada por los habitantes de Selinunte y llamada Heraclea en honor al héroe semidiós. Los hallazgos arqueológicos, sin embargo, cuentan una historia mucho más antigua y fascinante de la zona. El área arqueológica se encuentra en una situación magnífica, en una reserva natural, en el promontorio de Capo Bianco (a 75 m), con un acantilado de piedra caliza blanca (pendiente pronunciada) que se adentra en el mar, inclinado al oeste hacia el valle de Plàtani y al este hacia la playa. Los fragmentos encontrados en las capas debajo de la Necrópolis arcaica del siglo VI a.C. Los orígenes del asentamiento urbano se remontarían a la prehistoria, y precisamente al Neolítico (del 8.000 al 3.500 a. C. aproximadamente), mientras que las monedas antiguas encontradas atestiguan la presencia de una colonia fenicia. En las primeras fuentes históricas, la ciudad aparece indicada con tres nombres: Macara, o ciudad de Makar, del fenicio Heracles; Minoa, en efecto, que fue fundada, según la leyenda, por el rey de Creta Minos, que persiguió hasta aquí a Dédalo; finalmente Eraclea, una colonia espartana que confirma el nombre del lugar en honor al gran héroe griego. Después de los fenicios y los espartanos, en el siglo V a.C., la ciudad se convirtió en una subcolonia de Selinunte y alcanzó el apogeo de su desarrollo en la época helenística (finales del siglo IV a.C.). Disputada durante mucho tiempo entre griegos y cartagineses por su posición fronteriza estratégica, cambió de manos varias veces hasta que, en el 210 a.C., fue conquistada por los romanos. En el siglo I a.C. quedó definitivamente abandonado, quizás debido a un desprendimiento de tierra que arrastró la parte sur del pueblo y las murallas hacia el mar. Las investigaciones arqueológicas, a principios del siglo XX, sacaron a la luz una parte del barrio residencial, con huellas legibles en dos estratificaciones sucesivas, de la ciudad arcaica y helenística, el tramo norte de las murallas de la ciudad, con restos de torres y puertas. , y el hermoso teatro con el proscenio abierto hacia el mar (parcialmente oculto por una estructura protectora). En el Antiquarium, a la entrada de la zona arqueológica, se expone material procedente de las casas y de las necrópolis arcaicas y helenísticas. El pueblo, situado más abajo que el sitio arqueológico, alberga instalaciones turísticas y de alojamiento, incluido un camping, a la sombra de un bosque de eucaliptos. La playa se extiende en forma de anfiteatro hasta las paredes rocosas de Capo Bianco, que con su barro ofrece a los bañistas tratamientos cosméticos naturales y gratuitos al aire libre.",
        },
      },
      {
        id: "1-2",
        title: {
          italian: "Fiume Platani",
          english: "Platani river",
          french: "Rivière Platani",
          spanish: "Río Platani",
        },
        images: ["/assets/home_platani.webp", "/assets/platani.webp"],
        description: {
          italian:
            "La Riserva Naturale Foce del fiume Platani è un’area naturale protetta della Sicilia sudoccidentale istituita per garantire la conservazione della popolazione ornitica, favorire la ricostituzione della macchia mediterranea e delle dune. La foce del fiume Platani è un luogo di incantevole bellezza naturalistica su cui domina la falesia di Capo Bianco. Quest'area rappresenta il primo approdo per molti uccelli migratori provenienti dall'Africa e, grazie alla diversificazione degli ambienti, offre rifugio ad una flora rigogliosa e variegata, quindi ad un'avifauna ricca e composita. La riserva che interseca la foce del fiume Platani nei territori di Ribera e Cattolica Eraclea (AG) comprende alcune delle spiagge sabbiose più integre della Sicilia oltre che cordoni dunali che ospitano comunità vegetali sia naturali che artificiali. Elementi caratteristici dell’area sono anche promontori e falesie costituiti da calcari marnosi e marne a globigerine, (Trubbi) oltre che calanchi argillosi. Ad est della Riserva, sul marnoso promontorio di Capo Bianco, sorgono le rovine della città greca di Eraclea-Minoa, di cui sono stati riportati alla luce i resti di un teatro e di un centro abitato. Nel complesso il sito presenta elevata valenza sia sotto l’aspetto paesaggistico che sotto quello prettamente naturalistico.",
          english:
            "The Mouth of the Platani River Nature Reserve is a protected natural area in southwestern Sicily established to ensure the conservation of the ornithic population, encourage the reconstitution of Mediterranean scrub and dunes. The mouth of the Platani River is a place of enchanting natural beauty overlooked by the Capo Bianco cliff. This area is the first port of call for many migratory birds from Africa and, thanks to the diversification of the environments, offers refuge to a lush and varied flora, thus to a rich and composite avifauna. The reserve, which intersects the mouth of the Platani River in the territories of Ribera and Cattolica Eraclea (AG), includes some of the most intact sandy beaches in Sicily as well as dune cordons that host both natural and artificial plant communities. Also characteristic elements of the area are headlands and cliffs consisting of marly limestone and globigerine marls, (Trubbi) as well as clayey gullies. To the east of the Reserve, on the marly promontory of Capo Bianco, stand the ruins of the Greek city of Heraclea-Minoa, of which the remains of a theater and settlement have been unearthed. Overall, the site is of high value from both a landscape and a purely naturalistic point of view.",
          french:
            "La réserve naturelle de l'embouchure du fleuve Platani est une zone naturelle protégée du sud-ouest de la Sicile créée pour garantir la conservation de la population d'oiseaux et encourager la reconstitution du maquis et des dunes méditerranéennes. L'embouchure de la rivière Platani est un lieu d'une beauté naturelle enchanteresse surplombé par la falaise de Capo Bianco. Cette zone représente le premier lieu d'atterrissage de nombreux oiseaux migrateurs venus d'Afrique et, grâce à la diversification des milieux, offre refuge à une flore luxuriante et variée, donc à une avifaune riche et composite. La réserve qui croise l'embouchure du fleuve Platani dans les territoires de Ribera et Cattolica Eraclea (AG) comprend certaines des plages de sable les plus intactes de Sicile ainsi que des ceintures de dunes qui abritent des communautés végétales naturelles et artificielles. Les éléments caractéristiques de la région sont également des promontoires et des falaises constitués de marnes calcaires et de marnes globigérinées (Trubbi) ainsi que des ravines argileuses. A l'est de la Réserve, sur le promontoire marneux de Capo Bianco, se dressent les ruines de la ville grecque d'Eraclea-Minoa, dont les restes d'un théâtre et d'une ville ont été mis au jour. Dans l’ensemble, le site présente une grande valeur tant d’un point de vue paysager que purement naturaliste.",
          spanish:
            "La Reserva Natural de Foce del fiume Platani es un área natural protegida del suroeste de Sicilia creada para garantizar la conservación de la población ornitológica y fomentar la reconstitución del maquis y las dunas mediterráneas. La desembocadura del río Platani es un lugar de encantadora belleza natural dominado por el acantilado de Capo Bianco. Esta zona es el primer puerto de escala de muchas aves migratorias procedentes de África y, gracias a la diversificación de los ambientes, ofrece refugio a una flora exuberante y variada, por lo tanto a una avifauna rica y compuesta. La reserva que cruza la desembocadura del río Platani en los territorios de Ribera y Cattolica Eraclea (AG) incluye algunas de las playas de arena más intactas de Sicilia, así como cinturones de dunas que albergan comunidades vegetales tanto naturales como artificiales. También son característicos de la zona los promontorios y acantilados formados por calizas margosas y margas globigerinas (Trubbi), así como los barrancos arcillosos. Al este de la Reserva, en el promontorio margoso de Capo Bianco, se encuentran las ruinas de la ciudad griega de Heraclea-Minoa, de la que se han sacado a la luz restos de un teatro y un asentamiento. En conjunto, el sitio es de gran valor tanto desde el punto de vista paisajístico como desde el puramente naturalista.",
        },
      },
    ],
  },
  {
    id: "2",
    title: {
      italian: "L'area archeologica",
      english: "The archaeological area",
      french: "La zone archéologique",
      spanish: "La zona arqueológica",
    },
    image: "/assets/teatro_greco.webp",
    roadmap: "/Percorsi",
    subcategory: [
      {
        id: "2-1",
        title: {
          italian: "L'area archeologica",
          english: "The archaeological area",
          french: "La zone archéologique",
          spanish: "La zona arqueológica",
        },
        images: ["path", "path"],
        description: {
          italian:
            "L’Area archeologica di Eraclea Minoa sorge su un bianco promontorio proteso verso uno splendido paesaggio marino, all’interno della Riserva Naturale della Foce del Fiume Platani. Le prime tracce di frequentazione dell’altopiano di Capobianco risalgono alla preistoria, cui si riferiscono anche i miti che rimandano alla presenza di popolazioni provenienti dall’Egeo dopo il crollo dei regni micenei. Un mito infatti collega il nome di Minoa con il re cretese Minosse e la spedizione in Sicilia che lo condusse alla morte presso il re sicano Kokalos. La colonia greca fu fondata intorno alla metà del VI secolo a. C. da Selinunte, Contesa a lungo e con alterne vicende fra Selinunte e Akragas, ben presto la città seguì lo stesso destino delle due contendenti cadendo in mano cartaginese. Per tutto il IV secolo a. C. la sua storia fu segnata dagli scontri fra Greci e Cartaginesi, finché nel III secolo a.C. non fu conquistata da Roma diventando civitas decumana. Verso la fine del I sec. a. C. la città fu abbandonata e solo in epoca paleocristiana e bizantina (III-VII sec. d. C.) l’area extra urbana tornò ad essere frequentata con la costruzione di una grande basilica con annesso un cimitero. Le prime campagne di scavo ebbero inizio nel 1950 quando Ernesto De Miro riportò alla luce l’imponente teatro, risalente al IV sec. a.C. La colonia era protetta da una cinta muraria lunga circa 6 km che ancora oggi abbraccia l’intero altopiano fino al fiume Platani. Nel corso delle indagini archeologiche sono state individuate consistenti tracce dell’abitato organizzato secondo un disegno urbanistico regolare, a terrazze, con un sistema di strade ortogonali che delimitavano gli isolati. Gli edifici scavati rimandano a due fasi sovrapposte di frequentazione: la più antica di epoca ellenistica (IV-III sec. a. C.) e la più recente di epoca romana- repubblicana (II-I sec. a. C.). A nord est della città, aldilà della cinta muraria, sorgevano le necropoli. Scavi sistematici effettuati fra gli anni 60 e 80 del secolo scorso, hanno messo in luce sepolture databili all’epoca arcaica e a quella ellenistica, testimoniando la presenza contemporanea del rito dell’inumazione e della cremazione. Nei pressi del sito archeologico è possibile visitare il piccolo Antiquarium in cui si conservano alcuni materiali provenienti dagli scavi.",
          english:
            "The Archaeological Area of Heraclea Minoa stands on a white promontory jutting out into a splendid seascape, within the Platani River Mouth Nature Reserve. The earliest traces of frequentation of the Capobianco plateau date back to prehistoric times, to which myths also refer referring to the presence of populations from the Aegean after the collapse of the Mycenaean kingdoms. One myth in fact links the name of Minoa with the Cretan king Minos and the expedition to Sicily that led to his death at the Sican king Kokalos. The Greek colony was founded around the middle of the 6th century B. C. by Selinunte, Contended for a long time and with ups and downs between Selinunte and Akragas, soon the city followed the same fate as the two contenders, falling into Carthaginian hands. Throughout the 4th century B.C. its history was marked by clashes between Greeks and Carthaginians, until in the 3rd century B.C. it was conquered by Rome, becoming civitas decumana. Toward the end of the 1st cent. bc. C. the city was abandoned, and it was not until the early Christian and Byzantine periods (3rd-7th cent. A.D.) that the extra-urban area became frequented again with the construction of a large basilica with a cemetery attached. The first excavation campaigns began in 1950 when Ernesto De Miro unearthed the imposing theater, dating from the 4th century BC. The colony was protected by a wall about 6 km long that still encompasses the entire plateau up to the Platani River. In the course of archaeological investigations, substantial traces of the settlement organized according to a regular, terraced urban design with a system of orthogonal streets that delimited the blocks were identified. The excavated buildings hark back to two overlapping phases of frequentation: the oldest from the Hellenistic period (4th-3rd cent. B.C.) and the most recent from the Roman-Republican period (2nd-1st cent. B.C.). To the northeast of the city, beyond the city wall, stood the necropolis. Systematic excavations carried out between the 1960s and 1980s uncovered burials datable to the Archaic and Hellenistic periods, testifying to the simultaneous presence of the rite of inhumation and cremation. Near the archaeological site it is possible to visit the small Antiquarium in which some materials from the excavations are preserved.",
          french:
            "La zone archéologique d'Heraclea Minoa se trouve sur un promontoire blanc qui s'avance vers un splendide paysage marin, à l'intérieur de la réserve naturelle des Foce del Fiume Platani. Les premières traces de fréquentation du plateau du Capobianco remontent à la préhistoire, à laquelle les mythes font également référence en évoquant la présence de populations venues de la mer Égée après l'effondrement des royaumes mycéniens. Un mythe associe en effet le nom de Minoa au roi crétois Minos et à l'expédition en Sicile qui le conduisit à la mort aux mains du roi sicain Kokalos. La colonie grecque fut fondée vers le milieu du VIe siècle avant J.-C. par Sélinonte. Longtemps disputée, avec des fortunes alternées entre Sélinonte et Akragas, la ville suivit bientôt le même sort que les deux prétendants, tombant aux mains des Carthaginois. Tout au long du IVe siècle avant J.-C., son histoire est marquée par des affrontements entre Grecs et Carthaginois, jusqu'à sa conquête par Rome au IIIe siècle avant J.-C., où elle devient civitas decumana. Vers la fin du 1er siècle av. J.-C., la ville fut abandonnée et ce n'est qu'au début de la période chrétienne et byzantine (du IIIe au VIIe siècle après J.-C.) que la zone extra-urbaine fut à nouveau fréquentée avec la construction d'une grande basilique et d'un cimetière attenant. Les premières campagnes de fouilles ont débuté en 1950 lorsque Ernesto De Miro a mis au jour l'imposant théâtre datant du IVe siècle av. La colonie était protégée par une muraille d'environ 6 km de long, qui embrasse encore aujourd'hui tout le plateau jusqu'au fleuve Platani. Au cours des fouilles archéologiques, des traces substantielles de la colonie ont été identifiées, organisées selon un plan urbain régulier, en terrasses, avec un système de rues orthogonales qui délimitaient les blocs. Les bâtiments fouillés correspondent à deux phases d'occupation qui se chevauchent : la plus ancienne date de la période hellénistique (4e-3e siècle av. J.-C.) et la plus récente de la période romaine-républicaine (2e-1er siècle av. J.-C.). Au nord-est de la ville, au-delà des remparts, se trouve la nécropole. Des fouilles systématiques menées entre les années 1960 et 1980 ont révélé des sépultures datant des périodes archaïque et hellénistique, témoignant de la présence simultanée du rite d'inhumation et de crémation. À proximité du site archéologique, il est possible de visiter le petit Antiquarium où sont conservés certains matériaux issus des fouilles.",
          spanish:
            "La zona arqueológica de Heraclea Minoa se alza sobre un promontorio blanco que se adentra en un espléndido paisaje marino, dentro de la Reserva Natural de la desembocadura del río Platani. dentro de la Reserva Natural de la desembocadura del río Platani. Los primeros rastros de frecuentación de la meseta de Capobianco se remontan a la prehistoria, a la que también se refieren mitos que aluden a la presencia de poblaciones procedentes del Egeo tras el colapso de los reinos micénicos. Un mito de hecho vincula el nombre de Minoa con el rey cretense Minos y la expedición a Sicilia que le llevó a la muerte a manos del rey siciliano Kokalos. La colonia griega fue fundada a mediados del siglo VI a.C. por Selinunte, Disputada durante mucho tiempo y con alternancia de fortunas entre Selinunte y Akragas, la ciudad pronto siguió el mismo destino que los dos contendientes, cayendo en manos de los sicanos. dos contendientes, cayendo en manos cartaginesas. A lo largo del siglo IV a.C. su historia estuvo marcada por enfrentamientos entre griegos y cartagineses, hasta que fue conquistada por Roma en el siglo III a.C. y se convirtió en civitas decumana. Hacia finales del siglo I a.C. A.C. la ciudad fue abandonada y sólo en los primeros periodos cristiano y bizantino (s. III a VII d C.) se abandonó la zona extraurbana. C.) la zona extraurbana volvió a ser frecuentada con la construcción de una gran basílica con un cementerio contiguo. cementerio. Las primeras campañas de excavación comenzaron en 1950, cuando Ernesto De Miró sacó a la luz el imponente teatro, que data del siglo IV a.C. La colonia estaba protegida por una muralla de unos 6 km de longitud que todavía abarca toda la meseta hasta el río Platani. En el curso de las investigaciones arqueológicas se identificaron importantes vestigios del asentamiento, organizado según un diseño urbano regular en terrazas, con un terrazas, con un sistema de calles ortogonales que delimitaban las manzanas. Los edificios excavados se refieren a dos fases de ocupación superpuestas: la más antigua del periodo helenístico (siglos IV-III a.C.) y la más reciente del romano-republicano (s. II-I a.C.). Al noreste de la ciudad, más allá de las murallas, se encontraba la necrópolis. necrópolis. Las excavaciones sistemáticas llevadas a cabo entre los años 1960 y 1980 revelaron enterramientos de los periodos arcaico y helenístico, que atestiguan la presencia simultánea de los ritos de inhumación e incineración. de inhumación e incineración. Cerca del yacimiento arqueológico se puede visitar el pequeño Antiquarium en el que se conservan algunos materiales procedentes de las excavaciones.",
        },
      },
      {
        id: "2-2",
        title: {
          italian: "Teatro di Eraclea",
          english: "Heraclea Theater",
          french: "Théâtre d'Héraclée",
          spanish: "Teatro de Heraclea",
        },
        images: ["path", "path"],
        description: {
          italian:
            "L’antico teatro greco di Eraclea, costruito alla fine del V a.C., fu riportato alla luce nel 1957. Esso si presenta con una cavea a 10 gradoni, divisa in 9 settori, che guarda verso il mare. Costruito ad incastro con conci di marna, il sito è dotato anche di antiquarium, dove sono conservati reperti archeologici rinvenuti durante le varie campagne di scavo. Gli scavi archeologici sulle rovine vennero intrapresi in modo sistematico dal 1950. La città viene considerata idonea per comprendere l’urbanistica delle città ellenistiche e romane: il teatro; il quartiere delle abitazioni ellenistiche e romane con impianto urbanistico ad “insulae”, separate da strade parallele. Si possono vedere anche i resti della cinta muraria della città costruita tra la fine del VI e la fine del IV secolo a.C., lungo circa 6 chilometri; a nord-est delle mura si riconoscono ancora otto torri quadrate. Il teatro greco fu individuato nel Settecento, ma portato alla luce soltanto nel 1953.",
          english:
            "The ancient Greek theater of Heraclea, built at the end of the fifth century BC, was unearthed in 1957. It features a 10-tiered cavea, divided into 9 sectors, looking toward the sea. Built interlocking with marl ashlars, the site also has an antiquarium, where archaeological finds unearthed during various excavation campaigns are preserved. Archaeological excavations on the ruins were undertaken systematically from 1950. The city is considered suitable for understanding the urban planning of Hellenistic and Roman cities: the theater; the neighborhood of Hellenistic and Roman dwellings with urban layout in “insulae,” separated by parallel streets. The remains of the city walls built between the late 6th and late 4th centuries B.C., about 6 kilometers long, can also be seen; eight square towers can still be recognized to the northeast of the walls. The Greek theater was identified in the 18th century, but not brought to light until 1953.",
          french:
            "Le théâtre grec antique d'Héraclée, construit à la fin du Ve siècle avant J.-C., a été mis au jour en 1957. Il possède une cavea à 10 gradins, divisée en 9 secteurs, donnant sur la mer. Construit en pierres de taille marneuses imbriquées les unes dans les autres, le site possède également un antiquarium, où sont conservés les objets archéologiques trouvés lors des différentes campagnes de fouilles. Des fouilles archéologiques sur les ruines ont été entreprises systématiquement depuis 1950. La ville est considérée comme adaptée à la compréhension de l'urbanisme des villes hellénistiques et romaines : le théâtre, le quartier d'habitations hellénistiques et romaines avec un plan urbain en « insulae », séparées par des rues parallèles. Les vestiges des remparts construits entre la fin du VIe et la fin du IVe siècle av. J.-C. sont également visibles, sur une longueur d'environ 6 kilomètres ; huit tours carrées sont encore reconnaissables au nord-est des remparts. Le théâtre grec a été identifié au XVIIIe siècle, mais n'a été mis au jour qu'en 1953.",
          spanish:
            "El antiguo teatro griego de Heraclea, construido a finales del siglo V a.C., salió a la luz en 1957. Cuenta con una cavea de 10 gradas, dividida en 9 sectores, que mira hacia el mar. Construido con sillares de marga entrelazados, el yacimiento cuenta también con un anticuario, donde se conservan los objetos arqueológicos hallados durante diversas campañas de excavación. Desde 1950 se realizan sistemáticamente excavaciones arqueológicas en las ruinas. La ciudad se considera idónea para comprender el urbanismo de las ciudades helenísticas y romanas: el teatro; el barrio de viviendas helenísticas y romanas con un trazado urbano de «insulae», separadas por calles paralelas. También pueden verse los restos de las murallas de la ciudad construidas entre finales del siglo VI y finales del siglo IV a.C., de unos 6 kilómetros de longitud; aún pueden reconocerse ocho torres cuadradas al noreste de las murallas. El teatro griego se identificó en el siglo XVIII, pero no salió a la luz hasta 1953.",
        },
      },
      {
        id: "2-3",
        title: {
          italian: "Antiquarium",
          english: "Antiquarium",
          french: "Antiquarium",
          spanish: "Antiquarium",
        },
        images: ["path", "path"],
        description: {
          italian:
            "L'Antiquarium di Eraclea Minoa è un museo situato all'ingresso dell'area archeologica della città. Al suo interno sono esposti reperti provenienti dalle abitazioni e dalle necropoli arcaiche ed ellenistiche. Tra i reperti figurano ceramiche, monete e altri oggetti che testimoniano la vita quotidiana e le influenze culturali della città nel corso dei secoli. L'Antiquarium offre un prezioso contesto storico per comprendere meglio l'evoluzione della città di Eraclea Minoa, dalla sua fondazione fino al suo declino.",
          english:
            "The Antiquarium of Heraclea Minoa is a museum located at the entrance to the city's archaeological area. On display inside are artifacts from the Archaic and Hellenistic dwellings and necropolises. The exhibits include ceramics, coins, and other objects that testify to the city's daily life and cultural influences over the centuries. The Antiquarium provides a valuable historical context for better understanding the evolution of the city of Heraclea Minoa, from its founding to its decline.",
          french:
            "L'Antiquarium d'Heraclea Minoa est un musée situé à l'entrée de la zone archéologique de la ville. Il expose des objets provenant des habitations et des nécropoles archaïques et hellénistiques. Les pièces exposées comprennent des céramiques, des pièces de monnaie et d'autres objets qui témoignent de la vie quotidienne et des influences culturelles de la ville au fil des siècles. L'Antiquarium fournit un contexte historique précieux pour mieux comprendre l'évolution de la ville d'Heraclea Minoa, de sa fondation à son déclin.",
          spanish:
            "El Antiquarium de Heraclea Minoa es un museo situado a la entrada de la zona arqueológica de la ciudad. En él se exponen objetos procedentes de las viviendas y necrópolis arcaicas y helenísticas. Los objetos expuestos incluyen cerámicas, monedas y otros objetos que dan testimonio de la vida cotidiana y las influencias culturales de la ciudad a lo largo de los siglos. El Antiquarium proporciona un valioso contexto histórico para comprender mejor la evolución de la ciudad de Heraclea Minoa, desde su fundación hasta su decadencia.",
        },
      },
    ],
  },
];

export default eracleaData;
